### ISSUE TITLE
Trung - Assessment #12

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/quoc-trung-assessment-12#1]

**Comment by longhypepoly** [comment]
Tất cả yêu cầu em đều đáp ứng được, nhưng có 1 cái bug đó là ở màn hình main lại hiển thị message mờ như hình dưới, em remove nó đi nhé 😉 


![Image](https://user-images.githubusercontent.com/116874636/205943270-0430e157-dcad-417b-b176-8fdde63ec601.png)

**Comment by quoctrungvu1610** [comment]
dạ anh long

**Comment by longhypepoly** [comment]
Perfect
